# Generated by Django 4.2.3 on 2023-07-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholeshopview', '0002_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=2500)),
                ('image', models.ImageField(upload_to='type_images')),
            ],
        ),
    ]
