# Generated by Django 4.2.4 on 2023-08-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_profile_address_alter_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
