# Generated by Django 4.2.4 on 2023-09-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_location', models.CharField(max_length=255)),
                ('work_hours', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('office_location', models.CharField(max_length=255)),
            ],
        ),
    ]
