# Generated by Django 4.2.4 on 2023-08-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tracking_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
