# Generated by Django 4.2.4 on 2023-08-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='tracking_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
